Add create /tmp/appimgman.lock file while running to prevent multiple instances Change help output to remove Bintray specific things Fix comments in code and start adding more comments

diff --git a/appimgman b/appimgman
--- a/appimgman
+++ b/appimgman
@@ -6,7 +6,7 @@
 # Website: http://www.simonizor.gq
 # License: GPL v2.0 only
 
-X="0.1.1"
+X="0.1.2"
 
 helpfunc () {
 printf '%s\n' "appimgman $X
@@ -27,7 +27,7 @@ allow AppImages that have the same name as existing commands on your system to b
 Arguments:
     list (-l) - list all installed AppImages and all AppImages known by appimgman or info about the specified AppImage
     list-installed (-li) - list all installed AppImages and install info
-    install (-i) - install an AppImage automatically if in AppImages-bintray.lst
+    install (-i) - install an AppImage
     remove (-r) - remove an installed AppImage
     update (-upd) - update AppImages-bintray.lst from appimgman's github repo and check for AppImage upgrades
     update-force (-updf) - add specified AppImage to upgrade-list without checking versions
@@ -40,7 +40,7 @@ installed using appimgman.  Please report any bugs that are specific to
 installed applications to their maintainers."
 }
 
-appimgvercheckfunc () { # Check version by getting the latest version from the bintray website using wget, grep, cut, and head
+appimgvercheckfunc () { # Check version by getting the latest version from the bintray website or github releases page using wget, grep, cut, and head
     if [ -f ~/.config/appimgman/installed/"$INSTIMG" ]; then
         . ~/.config/appimgman/installed/"$INSTIMG"
     fi
@@ -108,7 +108,7 @@ updatelistfunc () { # Regenerate AppImages-bintray.lst from bintray, download Ap
     echo "AppImages-bintray.lst updated!"
     echo "Downloading AppImages-github.lst from appimgman github repo..."
     rm ~/.config/appimgman/AppImages-github.lst
-    wget --quiet --show-progress "https://raw.githubusercontent.com/simoniz0r/appimgman/master/AppImages-github.lst" || { echo "wget failed; exiting..."; exit 1; }
+    wget --quiet --show-progress "https://raw.githubusercontent.com/simoniz0r/appimgman/master/AppImages-github.lst" || { echo "wget failed; exiting..."; rm /tmp/appimgman.lock; exit 1; }
     echo "AppImages-github.lst updated!"
     if [ ! -f ~/.config/appimgman/upgrade-list.lst ]; then
         touch ~/.config/appimgman/upgrade-list.lst
@@ -145,6 +145,7 @@ updatelistfunc () { # Regenerate AppImages-bintray.lst from bintray, download Ap
         if grep -qw "$2" ~/.config/appimgman/upgrade-list.lst; then
             echo "$(tput setaf 2)$2 is already marked for upgrade!"
             echo "Run 'appimgman upgrade $2' to upgrade $2$(tput sgr0)"
+            rm /tmp/appimgman.lock
             exit 0
         fi
         INSTIMG="$2"
@@ -161,13 +162,13 @@ updatelistfunc () { # Regenerate AppImages-bintray.lst from bintray, download Ap
             rm ~/.config/appimgman/upgrade-list.lst
         fi
     fi
-    rm -rf ~/.config/appimgman/cache/*
+    rm /tmp/appimgman.lock
 }
 
 appimgdlfunc () { # wget latest url from bintray website or github repo and wget it
     if [ "$BINTRAY_IMG" = "TRUE" ]; then
         APPIMAGE="$(wget -q "https://bintray.com/package/files/probono/AppImages/$APPIMG_NAME?order=desc&sort=fileLastModified&basePath=&tab=files" -O - | grep -e '64.AppImage">' | cut -d '"' -f 6 | head -n 1)"
-        wget --show-progress --quiet "https://bintray.com/$APPIMAGE" -O ~/.config/appimgman/cache/"$INSTIMG" || { echo "wget $APPIMAGE failed; exiting..."; exit 1; }
+        wget --show-progress --quiet "https://bintray.com/$APPIMAGE" -O ~/.config/appimgman/cache/"$INSTIMG" || { echo "wget $APPIMAGE failed; exiting..."; rm /tmp/appimgman.lock; exit 1; }
         APPIMAGE="$(echo "$APPIMAGE" | cut -f2 -d"=")"
     elif [ "$GITHUB_IMG" = "TRUE" ]; then
         GITHUB_APP_URL="$(grep -wi "$INSTIMG" ~/.config/appimgman/AppImages-github.lst | cut -f2- -d" ")"
@@ -176,7 +177,7 @@ appimgdlfunc () { # wget latest url from bintray website or github repo and wget
             APPIMAGE_URL="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*/download/.*.AppImage' | head -n 1 | cut -f2 -d'"')"
         fi
         APPIMAGE="${APPIMAGE_URL##*/}"
-        wget --show-progress --quiet "https://github.com/$APPIMAGE_URL" -O ~/.config/appimgman/cache/"$INSTIMG" || { echo "wget $APPIMAGE_URL failed; exiting..."; exit 1; }
+        wget --show-progress --quiet "https://github.com/$APPIMAGE_URL" -O ~/.config/appimgman/cache/"$INSTIMG" || { echo "wget $APPIMAGE_URL failed; exiting..."; rm /tmp/appimgman.lock; exit 1; }
     fi
 }
 
@@ -187,6 +188,7 @@ appimginstallfunc () { # chmod and mv AppImages to /usr/local/bin and create fil
     echo "BIN_PATH="\"/usr/local/bin/$INSTIMG\""" > ~/.config/appimgman/installed/"$INSTIMG"
     echo "APPIMAGE="\"$APPIMAGE\""" >> ~/.config/appimgman/installed/"$INSTIMG"
     echo "$APPIMAGE has been installed to /usr/local/bin/$INSTIMG !"
+    rm /tmp/appimgman.lock
     exit 0
 }
 
@@ -208,6 +210,7 @@ appimgremovefunc () { # rm AppImage in /usr/local/bin and remove install info fi
     case $IMGREMANSWER in
         N*|n*)
             echo "$REMIMG was not removed."
+            rm /tmp/appimgman.lock
             exit 0
             ;;
     esac
@@ -225,6 +228,7 @@ appimgremovefunc () { # rm AppImage in /usr/local/bin and remove install info fi
     sudo rm /usr/local/bin/"$REMIMG"
     rm ~/.config/appimgman/installed/"$REMIMG"
     echo "$REMIMG has been removed!"
+    rm /tmp/appimgman.lock
     exit 0
 }
 
@@ -233,7 +237,12 @@ if [ "$EUID" = "0" ]; then
     exit 1
 fi
 
-rm -rf ~/.config/appimgman/cache/*
+if [ ! -f /tmp/appimgman.lock ]; then
+    touch /tmp/appimgman.lock
+else
+    echo "appimgman is currently running or did not exit properly; exiting..."
+    exit 1
+fi
 
 if [ ! -d ~/.config/appimgman ]; then # Create dirs for configs if they don't exist
     echo "appimgman is being ran for the first time."
@@ -249,32 +258,38 @@ if [ ! -d ~/.config/appimgman ]; then # Create dirs for configs if they don't ex
 fi
 
 case $1 in
-    install|-i) # Install: check appimg against known list, if not known, send to custom install func, else send to regular install func
+    install|-i) # Check if app is already installed either by appimgman or otherwise then install app to /usr/local/bin if it is in known lists
         if [ -z "$2" ]; then
             echo "AppImage input required; exiting..."
+            rm /tmp/appimgman.lock
             exit 1
         fi
         INSTIMG="$2"
         if [ -f ~/.config/appimgman/installed/"$INSTIMG" ]; then
             echo "$INSTIMG is already installed."
             echo "Use 'appimgman upgrade' to install the latest version of $INSTIMG."
+            rm /tmp/appimgman.lock
             exit 1
         fi
         if type >/dev/null 2>&1 "$INSTIMG"; then
             echo "$INSTIMG is already installed and not managed by appimgman; exiting..."
+            rm /tmp/appimgman.lock
             exit 1
         fi
         if [ -f "/usr/local/bin/$INSTIMG" ]; then
             echo "/usr/local/bin/$INSTIMG exists; exiting..."
+            rm /tmp/appimgman.lock
             exit 1
         fi
         appcheckfunc "$INSTIMG"
         appimgvercheckfunc
         if [ "$APPIMAGE_ERROR" = "TRUE" ]; then
+            rm /tmp/appimgman.lock
             exit 1
         fi
         if [ "$BINTRAY_IMG" = "FALSE" ] && [ "$GITHUB_IMG" = "FALSE" ];then
             echo "$INSTIMG is not in AppImages-bintray.lst or AppImages-github.lst; try running 'appimgman update'."
+            rm /tmp/appimgman.lock
             exit 1
         else
             echo "$NEW_APPIMAGE will be installed to /usr/local/bin/$INSTIMG"
@@ -282,7 +297,7 @@ case $1 in
             case $INSTANSWER in
                 N*|n*)
                     echo "$NEW_APPIMAGE was not installed."
-                    rm -rf ~/.config/appimgman/cache/*
+                    rm /tmp/appimgman.lock
                     exit 0
                     ;;
             esac
@@ -290,7 +305,7 @@ case $1 in
         appimgdlfunc "$INSTIMG"
         appimginstallfunc
         ;;
-    update|-upd) # Download latest AppImages-bintray.lst and check version from install info stored in ~/.config/appimgman/installed against latest url
+    update|-upd) # Update AppImage lists and check version from install info stored in ~/.config/appimgman/installed against latest url
         updatelistfunc "$@"
         ;;
     update-force|-updf) # Force specified AppImage to be upgraded by adding it to the upgrade-list.lst
@@ -305,6 +320,7 @@ case $1 in
             if grep -qw "$INSTIMG" ~/.config/appimgman/upgrade-list.lst; then
                 echo "$(tput setaf 2)$INSTIMG is already marked for upgrade!"
                 echo "Run 'appimgman upgrade $INSTIMG' to upgrade $INSTIMG$(tput sgr0)"
+                rm /tmp/appimgman.lock
                 exit 0
             fi
         fi
@@ -322,6 +338,7 @@ case $1 in
     upgrade|-upg) # upgrade AppImages to latest version if on upgrade-list.lst; update argument must be ran to put them on update-list.lst
         if [ ! -f ~/.config/appimgman/upgrade-list.lst ]; then
             echo "No upgrades available; try running 'appimgman update'."
+            rm /tmp/appimgman.lock
             exit 0
         fi
         if [ -z "$2" ]; then
@@ -346,17 +363,17 @@ case $1 in
                         appcheckfunc "$INSTIMG"
                         appimgdlfunc "$INSTIMG"
                         appimgupgradefunc
-                        rm -rf ~/.config/appimgman/cache/*
                         echo
                     done
+                    rm /tmp/appimgman.lock
                     ;;
                 N*|n*)
                     echo "No AppImages were upgraded; exiting..."
-                    rm -rf ~/.config/appimgman/cache/*
+                    rm /tmp/appimgman.lock
                     exit 0
                     ;;
             esac
-            rm -rf ~/.config/appimgman/cache/*
+            rm /tmp/appimgman.lock
             rm -f ~/.config/appimgman/upgrade-list.lst
             exit 0
         elif grep -qw "$2" ~/.config/appimgman/upgrade-list.lst; then
@@ -374,22 +391,25 @@ case $1 in
                         sed -i "s:"$INSTIMG"::g" ~/.config/appimgman/upgrade-list.lst
                         sed -i '/^$/d' ~/.config/appimgman/upgrade-list.lst
                     fi
-                    rm -rf ~/.config/appimgman/cache/*
+                    rm /tmp/appimgman.lock
                     exit 0
                     ;;
                 N*|n*)
                     echo "$INSTIMG was not upgraded."
+                    rm /tmp/appimgman.lock
                     exit 0
                     ;;
             esac
         else
-            echo "No new upgrade for $2; try running 'appimgman upgrade'."
+            echo "No new upgrade for $2; try running 'appimgman update'."
+            rm /tmp/appimgman.lock
             exit 0
         fi
         ;;
     remove|-r) # rm AppImage from /usr/local/bin and rm install info in ~/.config/appimgman/installed
         if [ -z "$2" ]; then
             echo "AppImage input required; exiting..."
+            rm /tmp/appimgman.lock
             exit 1
         fi
         REMIMG="$2"
@@ -398,6 +418,7 @@ case $1 in
             cat ~/.config/appimgman/installed/"$REMIMG"
         else
             echo "AppImage not found!"
+            rm /tmp/appimgman.lock
             exit 1
         fi
         appimgremovefunc
@@ -436,9 +457,11 @@ case $1 in
                 echo "INSTALLED=\"NO\""
             else
                 echo "AppImage not found!"
+                rm /tmp/appimgman.lock
                 exit 1
             fi
         fi
+        rm /tmp/appimgman.lock
         ;;
     list-installed|-li) # List information about installed AppImages
         echo "$(dir -C -w 1 ~/.config/appimgman/installed | wc -l) AppImages installed:"
@@ -450,8 +473,10 @@ case $1 in
             echo "INSTALLED=\"YES\""
             echo
         done
+        rm /tmp/appimgman.lock
         ;;
     *) # Any unknown arguments go to help func
         helpfunc
+        rm /tmp/appimgman.lock
         ;;
 esac
