Change github AppImage checks to use regular github webpage instead of API to avoid rate limiting

diff --git a/appimgman b/appimgman
--- a/appimgman
+++ b/appimgman
@@ -6,7 +6,7 @@
 # Website: http://www.simonizor.gq
 # License: GPL v2.0 only
 
-X="0.0.7"
+X="0.0.8"
 
 helpfunc () {
 printf '%s\n' "appimgman $X
@@ -61,9 +61,15 @@ appimgvercheckfunc () { # Check version by getting the latest version from the b
         fi
     elif [ "$GITHUB_IMG" = "TRUE" ]; then
         GITHUB_APP_URL="$(grep -wi "$INSTIMG" ~/.config/appimgman/AppImages-github.lst | cut -f2- -d" ")"
-        NEW_APPIMAGE="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*64.AppImage' | sed -n 2p | cut -f4- -d'"' | tr -d '"')"
+        NEW_APPIMAGE="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*64.AppImage' | head -n 1 | cut -f2 -d'"')"
         if [ -z "$NEW_APPIMAGE" ]; then
-            NEW_APPIMAGE="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*.AppImage' | sed -n 2p | cut -f4- -d'"' | tr -d '"')"
+            NEW_APPIMAGE="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*.AppImage' | head -n 1 | cut -f2 -d'"')"
+        fi
+        if [ -z "$NEW_APPIMAGE" ]; then
+            echo "Error checking $INSTIMG version; exiting..."
+            NEW_UPGRADE="FALSE"
+            APPIMAGE_ERROR="TRUE"
+            exit 1
         fi
         NEW_APPIMAGE="${NEW_APPIMAGE##*/}"
         if [ -z "$APPIMAGE" ]; then
@@ -177,22 +183,22 @@ updatelistfunc () { # Regenerate AppImages-bintray.lst from bintray, download Ap
     rm -rf ~/.config/appimgman/cache/*
 }
 
-appimgdlfunc () { # wget latest url from bintray website and wget it
+appimgdlfunc () { # wget latest url from bintray website or github repo and wget it
     if [ "$BINTRAY_IMG" = "TRUE" ]; then
         APPIMAGE="$(wget -q "https://bintray.com/package/files/probono/AppImages/$APPIMG_NAME?order=desc&sort=fileLastModified&basePath=&tab=files" -O - | grep -e '64.AppImage">' | cut -d '"' -f 6 | head -n 1)"
         wget --show-progress --quiet "https://bintray.com/$APPIMAGE" -O ~/.config/appimgman/cache/"$INSTIMG" || { echo "wget $APPIMAGE failed; exiting..."; exit 1; }
     elif [ "$GITHUB_IMG" = "TRUE" ]; then
         GITHUB_APP_URL="$(grep -wi "$INSTIMG" ~/.config/appimgman/AppImages-github.lst | cut -f2- -d" ")"
-        APPIMAGE_URL="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*64.AppImage' | sed -n 2p | cut -f4- -d'"' | tr -d '"')"
+        APPIMAGE_URL="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*64.AppImage' | head -n 1 | cut -f2 -d'"')"
         if [ -z "$APPIMAGE_URL" ]; then
-            APPIMAGE_URL="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*.AppImage' | sed -n 2p | cut -f4- -d'"' | tr -d '"')"
+            APPIMAGE_URL="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*.AppImage' | head -n 1 | cut -f2 -d'"')"
         fi
         APPIMAGE="${APPIMAGE_URL##*/}"
-        wget --show-progress --quiet "$APPIMAGE_URL" -O ~/.config/appimgman/cache/"$INSTIMG" || { echo "wget $APPIMAGE_URL failed; exiting..."; exit 1; }
+        wget --show-progress --quiet "https://github.com/$APPIMAGE_URL" -O ~/.config/appimgman/cache/"$INSTIMG" || { echo "wget $APPIMAGE_URL failed; exiting..."; exit 1; }
     fi
 }
 
-appimginstallfunc () { # chmod and mv bintray AppImages to /usr/local/bin and create file containing install info in ~/.config/appimgman/installed
+appimginstallfunc () { # chmod and mv AppImages to /usr/local/bin and create file containing install info in ~/.config/appimgman/installed
     chmod a+x ~/.config/appimgman/cache/"$INSTIMG"
     echo "Moving $INSTIMG to /usr/local/bin/$INSTIMG ..."
     sudo mv ~/.config/appimgman/cache/"$INSTIMG" /usr/local/bin/"$INSTIMG"
@@ -203,7 +209,7 @@ appimginstallfunc () { # chmod and mv bintray AppImages to /usr/local/bin and cr
     exit 0
 }
 
-appimgupgradefunc () { # rm old bintray AppImage, chmod, and mv new bintray AppImage to /usr/local/bin
+appimgupgradefunc () { # rm old AppImage, chmod, and mv new AppImage to /usr/local/bin
     echo "Removing previous $INSTIMG version..."
     sudo rm /usr/local/bin/"$INSTIMG"
     chmod a+x ~/.config/appimgman/cache/"$INSTIMG"
@@ -433,13 +439,14 @@ case $1 in
                 echo "INSTALLED=\"YES\""
             elif grep -qw "$2" ~/.config/appimgman/AppImages-bintray.lst; then
                 echo "$2 AppImage information:"
-                echo "APPIMAGE=\"$(wget -q "https://bintray.com/package/files/probono/AppImages/$2?order=desc&sort=fileLastModified&basePath=&tab=files" -O - | grep -e '64.AppImage">' | cut -d '"' -f 6 | head -n 1)\""
+                APPIMAGE="$(wget -q "https://bintray.com/package/files/probono/AppImages/$2?order=desc&sort=fileLastModified&basePath=&tab=files" -O - | grep -e '64.AppImage">' | cut -d '"' -f 6 | head -n 1)"
+                echo "APPIMAGE=\"${APPIMAGE##*/}\""
                 echo "INSTALLED=\"NO\""
             elif grep -qw "$2" ~/.config/appimgman/AppImages-github.lst; then
                 GITHUB_APP_URL="$(grep -w "$2" ~/.config/appimgman/AppImages-github.lst | cut -f2- -d" ")"
-                APPIMAGE="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*64.AppImage' | sed -n 2p | cut -f4- -d'"' | tr -d '"')"
+                APPIMAGE="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*64.AppImage' | head -n 1 | cut -f2 -d'"')"
                 if [ -z "$APPIMAGE" ]; then
-                    APPIMAGE="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*.AppImage' | sed -n 2p | cut -f4- -d'"' | tr -d '"')"
+                    APPIMAGE="$(wget --quiet "$GITHUB_APP_URL" -O - | grep -i '.*.AppImage' | head -n 1 | cut -f2 -d'"')"
                 fi
                 echo "$2 AppImage information:"
                 echo "APPIMAGE=\"${APPIMAGE##*/}\""
