Add error checks to all function calls from base script

diff --git a/spm b/spm
--- a/spm
+++ b/spm
@@ -56,7 +56,7 @@ else
         echo "spmfunctions.sh is missing! Please download the full release of spm from https://github.com/simoniz0r/spm/releases !$(tput sgr0)"
         exit 1
 fi
-source "$RUNNING_DIR"/spmfunctions.sh # import functions from spmfunctions.sh
+source "$RUNNING_DIR"/spmfunctions.sh || { echo "Sourcing spmfunctions.sh failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from spmfunctions.sh
 
 spmdepchecksfunc || { echo "$(tput setaf 1)Could not load $RUNNING_DIR/spmfunctions.sh; exiting...$(tput sgr0)"; exit 1; } # Check for deps, exit if not present
 
@@ -71,20 +71,20 @@ if type spm >/dev/null 2>&1 && [ -f ~/.zshrc ] && ! grep -q 'spm.comp' ~/.zshrc;
 fi
 
 appimgfunctioncheckfunc # Check to make sure appimgfunctions.sh exists and is up to date
-source "$RUNNING_DIR"/appimgfunctions.sh # import functions from appimgfunctions.sh
+source "$RUNNING_DIR"/appimgfunctions.sh || { echo "Sourcing appingfunctions.sh failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from appimgfunctions.sh
 appimgfunctionsexistsfunc  || { echo "$(tput setaf 1)Could not load $RUNNING_DIR/appimgfunctions.sh; exiting...$(tput sgr0)"; exit 1; }
 
 tarfunctioncheckfunc # Check to make sure tarfunctions.sh exists and is up to date
-source "$RUNNING_DIR"/tarfunctions.sh # import functions from tarfunctions.sh
+source "$RUNNING_DIR"/tarfunctions.sh || { echo "Sourcing tarfunctions.sh failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from tarfunctions.sh
 tarfunctionsexistfunc || { echo "$(tput setaf 1)Could not load $RUNNING_DIR/tarfunctions.sh; exiting...$(tput sgr0)"; exit 1; }
 
 spmlockfunc # Create "$CONFDIR"/cache/spm.lock file and prevent multiple instances by checking if it exists before running
 
 if [ -z "$GITHUB_TOKEN" ]; then # Display github rate limit by using wget to show https://api.github.com/rate_limit
     wget -S --spider "https://api.github.com/rate_limit" -o "$CONFDIR"/cache/rate.limit
-    echo "Github API rate limit: $(grep -m 1 '.*X-RateLimit-Remaining:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ")/60 until $(date -d@$(grep -m 1 '.*X-RateLimit-Reset:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ") +"%T, %F")."
+    echo "Github API rate limit: $(grep -m 1 '.*X-RateLimit-Remaining:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ")/60 until $(date -d@$(grep -m 1 '.*X-RateLimit-Reset:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ") +"%T, %F")."  || { echo "Github rate limit check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
 else
-    wget -S --spider --quiet --auth-no-challenge --header="Authorization: token "$GITHUB_TOKEN"" "https://api.github.com/rate_limit" -o "$CONFDIR"/cache/rate.limit
+    wget -S --spider --quiet --auth-no-challenge --header="Authorization: token "$GITHUB_TOKEN"" "https://api.github.com/rate_limit" -o "$CONFDIR"/cache/rate.limit  || { echo "Github rate limit check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
     echo "Github API rate limit : $(grep -m 1 '.*X-RateLimit-Remaining:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ")/5000 until $(date -d@$(grep -m 1 '.*X-RateLimit-Reset:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ") +"%T, %F")."
 fi
 if [ "$(grep -m 1 '.*X-RateLimit-Remaining:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ")" = "0" ]; then # Attempt to exit to prevent errors if user's github rate limit has been used up
@@ -104,13 +104,13 @@ case $1 in
             exit 1
         fi
         TESTPKG="$2"
-        installstartfunc # Check package lists and route install to relevant function
+        installstartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check package lists and route install to relevant function
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
     update|-upd) # Update package lists and check for package upgrades
-        spmvercheckfunc # Check spm version and let user know if it is out of date
-        updatestartfunc "$2" # Send input to relevant update function or run both if no input
+        spmvercheckfunc || { echo "spm version check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check spm version and let user know if it is out of date
+        updatestartfunc "$2" || { echo "Upgrade check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Send input to relevant update function or run both if no input
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
@@ -121,12 +121,12 @@ case $1 in
             exit 1
         fi
         TESTUF="$2"
-        updateforcestartfunc
+        updateforcestartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
     upgrade|-upg) # upgrade packages to latest version if marked for upgrade
-        upgradestartfunc "$2" # Check which (if any) package types have upgrades and run relevant functions
+        upgradestartfunc "$2" || { echo "Upgrade failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check which (if any) package types have upgrades and run relevant functions
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
@@ -137,25 +137,25 @@ case $1 in
             exit 1
         fi
         TESTREM="$2"
-        removestartfunc
+        removestartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
     list|-l) # List installed packages or info about specified package
         INSTIMG="$2"
         TARPKG="$2"
-        liststartfunc # Send package input to relevant list function or run both if no input
+        liststartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Send package input to relevant list function or run both if no input
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
     list-installed|-li) # List information about installed packages
         echo "$(tput bold)$(tput setaf 2)AppImages$(tput sgr0):"
         echo
-        appimglistinstalledfunc # List info about all installed AppImages
+        appimglistinstalledfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # List info about all installed AppImages
         echo
         echo "$(tput bold)$(tput setaf 6)tar packages$(tput sgr0):"
         echo
-        tarlistinstalledfunc # List info about all installed tar packages
+        tarlistinstalledfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # List info about all installed tar packages
         echo "$(tput bold)$(tput setaf 2)$(dir -C -w 1 "$CONFDIR"/appimginstalled | wc -l) AppImages installed$(tput sgr0):" # Output number of and names of installed AppImages
         dir -C -w 1 "$CONFDIR"/appimginstalled | pr -tT --column=3 -w 125
         echo
