Change more user friendly errors and prompts

diff --git a/spm b/spm
--- a/spm
+++ b/spm
@@ -6,7 +6,7 @@
 # Website: http://www.simonizor.gq
 # License: GPL v2.0 only
 
-X="0.5.9"
+X="0.6.0"
 # Set spm version
 CONFDIR="$HOME/.config/spm"
 SKIP_DEP_CHECKS="FALSE"
@@ -40,7 +40,6 @@ if [ ! -d "$CONFDIR" ]; then # Create dirs for configs, config files, and downlo
     echo "CONFDIR="\"$CONFDIR\""" > "$CONFDIR"/spm.conf
     echo "GITHUB_TOKEN="\"\""" >> "$CONFDIR"/spm.conf
     echo "SKIP_DEP_CHECKS="\"FALSE\""" >> "$CONFDIR"/spm.conf
-    echo "CLR_CLEAR="\"$(tput sgr0)\""" >> "$CONFDIR"/spm.conf
     echo "CLR_BLUE="\"$(tput setaf 4)\""" >> "$CONFDIR"/spm.conf
     echo "CLR_LGREEN="\"$(tput setaf 10)\""" >> "$CONFDIR"/spm.conf
     echo "CLR_GREEN="\"$(tput setaf 2)\""" >> "$CONFDIR"/spm.conf
@@ -59,21 +58,27 @@ fi
 
 REALPATH="$(readlink -f $0)"
 RUNNING_DIR="$(dirname "$REALPATH")" # Find directory script is running from
+if [ -f "$RUNNING_DIR/ssft.sh" ]; then
+    source "$RUNNING_DIR"/ssft.sh
+    SSFT_FRONTEND="text"
+else
+    echo "${CLR_RED}Missing required file $RUNNINGDIR/ssft.sh; exiting...${CLR_CLEAR}"
+    rm -rf "$CONFDIR"/cache/*
+    exit 1
+fi
 if [ -f $RUNNING_DIR/spmfunctions.sh ]; then # Check to make sure spmfunctions.sh exists and is up to date
     FUNCTIONS_VER="$(cat "$RUNNING_DIR"/spmfunctions.sh | sed -n 9p | cut -f2 -d'"')"
     if [ "$X" != "$FUNCTIONS_VER" ]; then
-        echo "${CLR_RED}spmfunctions.sh $FUNCTIONS_VER version does not match $X !"
-        echo "spmfunctions.sh is out of date! Please download the full release of spm from https://github.com/simoniz0r/spm/releases !${CLR_CLEAR}"
+        ssft_display_error "${CLR_RED}spmfunctions.sh $FUNCTIONS_VER version does not match $X !" "spmfunctions.sh is out of date! Please download the full release of spm from https://github.com/simoniz0r/spm/releases !${CLR_CLEAR}"
         exit 1
     fi
 else
-    echo "${CLR_RED}Missing required file $RUNNING_DIR/spmfunctions.sh !"
-        echo "spmfunctions.sh is missing! Please download the full release of spm from https://github.com/simoniz0r/spm/releases !${CLR_CLEAR}"
-        exit 1
+    ssft_display_error "${CLR_RED}Missing required file $RUNNING_DIR/spmfunctions.sh !" "spmfunctions.sh is missing! Please download the full release of spm from https://github.com/simoniz0r/spm/releases !${CLR_CLEAR}"
+    exit 1
 fi
-source "$RUNNING_DIR"/spmfunctions.sh || { echo "Sourcing spmfunctions.sh failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from spmfunctions.sh
+source "$RUNNING_DIR"/spmfunctions.sh || { ssft_display_error "${CLR_RED}Error sourcing spmfunctions.sh" "Sourcing spmfunctions.sh failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from spmfunctions.sh
 
-spmdepchecksfunc || { echo "${CLR_RED}Could not load $RUNNING_DIR/spmfunctions.sh; exiting...${CLR_CLEAR}"; exit 1; } # Check for deps, exit if not present
+spmdepchecksfunc || { ssft_display_error "${CLR_RED}Error loading spmfunctions.sh" "Could not load $RUNNING_DIR/spmfunctions.sh; exiting...${CLR_CLEAR}"; exit 1; } # Check for deps, exit if not present
 
 if type spm >/dev/null 2>&1 && [ -f ~/.zshrc ] && ! grep -q 'spm.comp' ~/.zshrc; then # If using zsh and spm is installed, add tab completions for spm
     wget --quiet "https://raw.githubusercontent.com/simoniz0r/spm/master/spm.comp" -O "$CONFDIR"/spm.comp
@@ -86,12 +91,12 @@ if type spm >/dev/null 2>&1 && [ -f ~/.zshrc ] && ! grep -q 'spm.comp' ~/.zshrc;
 fi
 
 appimgfunctioncheckfunc # Check to make sure appimgfunctions.sh exists and is up to date
-source "$RUNNING_DIR"/appimgfunctions.sh || { echo "Sourcing appingfunctions.sh failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from appimgfunctions.sh
-appimgfunctionsexistsfunc  || { echo "${CLR_RED}Could not load $RUNNING_DIR/appimgfunctions.sh; exiting...${CLR_CLEAR}"; exit 1; }
+source "$RUNNING_DIR"/appimgfunctions.sh || { ssft_display_error "${CLR_RED}Error sourcing appimgfunctions.sh" "Sourcing appingfunctions.sh failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from appimgfunctions.sh
+appimgfunctionsexistsfunc  || { ssft_display_error "${CLR_RED}Error loading appimgfunctions.sh" "Could not load $RUNNING_DIR/appimgfunctions.sh; exiting...${CLR_CLEAR}"; exit 1; }
 
 tarfunctioncheckfunc # Check to make sure tarfunctions.sh exists and is up to date
-source "$RUNNING_DIR"/tarfunctions.sh || { echo "Sourcing tarfunctions.sh failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from tarfunctions.sh
-tarfunctionsexistfunc || { echo "${CLR_RED}Could not load $RUNNING_DIR/tarfunctions.sh; exiting...${CLR_CLEAR}"; exit 1; }
+source "$RUNNING_DIR"/tarfunctions.sh || { ssft_display_error "${CLR_RED}Error sourcing tarfunctions.sh" "Sourcing tarfunctions.sh failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from tarfunctions.sh
+tarfunctionsexistfunc || { ssft_display_error "${CLR_RED}Error loading tarfunctions.sh" "Could not load $RUNNING_DIR/tarfunctions.sh; exiting...${CLR_CLEAR}"; exit 1; }
 
 spmlockfunc # Create "$CONFDIR"/cache/spm.lock file and prevent multiple instances by checking if it exists before running
 
@@ -103,9 +108,7 @@ else
     echo "Github API rate limit : $(grep -m 1 '.*X-RateLimit-Remaining:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ")/5000 until $(date -d@$(grep -m 1 '.*X-RateLimit-Reset:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ") +"%T, %F")."
 fi
 if [ "$(grep -m 1 '.*X-RateLimit-Remaining:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ")" = "0" ]; then # Attempt to exit to prevent errors if user's github rate limit has been used up
-    echo "${CLR_RED}Github API rate limit reached! Try again at $(date -d@$(grep -m 1 '.*X-RateLimit-Reset:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" "))."
-    echo "If you haven't already, you can add your token to $CONFDIR/spm.conf"
-    echo "to avoid hitting the rate limit.${CLR_CLEAR}"
+    ssft_display_error "${CLR_RED}Github API rate limit reached! Try again at $(date -d@$(grep -m 1 '.*X-RateLimit-Reset:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" "))." "If you haven't already, you can add your token to $CONFDIR/spm.conf to avoid hitting the rate limit.${CLR_CLEAR}"
     rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
     exit 1
 fi
@@ -114,52 +117,52 @@ echo
 case $1 in
     install|-i|appimg-install|-ai|tarinstall|-ti) # Check if package is in either list and rout install to relevant function
         if [ -z "$2" ]; then
-            echo "${CLR_RED}Package input required; exiting...${CLR_CLEAR}"
+            ssft_display_error "${CLR_RED}Error" "Package input required; exiting...${CLR_CLEAR}"
             rm -rf "$CONFDIR"/cache/*
             exit 1
         fi
         TESTPKG="$2"
-        installstartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check package lists and route install to relevant function
+        installstartfunc || { ssft_display_error "${CLR_RED}Error" "Install failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check package lists and route install to relevant function
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
     update|-upd) # Update package lists and check for package upgrades
-        spmvercheckfunc || { echo "spm version check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check spm version and let user know if it is out of date
-        updatestartfunc "$2" || { echo "Upgrade check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Send input to relevant update function or run both if no input
+        spmvercheckfunc || { ssft_display_error "${CLR_RED}Error" "spm version check failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check spm version and let user know if it is out of date
+        updatestartfunc "$2" || { sssft_display_error "${CLR_RED}Error" "Upgrade check failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; } # Send input to relevant update function or run both if no input
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
     update-force|-uf|appimg-update-force|-auf|tar-update-force|-tuf) # Force AppImage to be marked for upgrade
         if [ -z "$2" ]; then
-            echo "${CLR_RED}Package input required; exiting...${CLR_CLEAR}"
+            ssft_display_error "${CLR_RED}Error" "Package input required; exiting...${CLR_CLEAR}"
             rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
             exit 1
         fi
         TESTUF="$2"
-        updateforcestartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
+        updateforcestartfunc || { ssft_display_error "${CLR_RED}Error" "Update force failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; }
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
     upgrade|-upg) # upgrade packages to latest version if marked for upgrade
-        upgradestartfunc "$2" || { echo "Upgrade failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check which (if any) package types have upgrades and run relevant functions
+        upgradestartfunc "$2" || { ssft_display_error "${CLR_RED}Error" "Upgrade failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; }
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
     remove|-r|appimg-remove|-ar|tar-remove|-tr)
         if [ -z "$2" ]; then
-            echo "${CLR_RED}Package input required; exiting...${CLR_CLEAR}"
+            ssft_display_error "${CLR_RED}Error" "Package input required; exiting...${CLR_CLEAR}"
             rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
             exit 1
         fi
         TESTREM="$2"
-        removestartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
+        removestartfunc || { ssft_display_error "${CLR_RED}Error" "Package remove failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; }
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
     list|-l) # List installed packages or info about specified package
         INSTIMG="$2"
         TARPKG="$2"
-        liststartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Send package input to relevant list function or run both if no input
+        liststartfunc || { ssft_display_error "${CLR_RED}Error" "List failed; exiting...${CLR_CLEAR}"; rm -rf "$CONFDIR"/cache/*; exit 1; } # Send package input to relevant list function or run both if no input
         rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
         exit 0
         ;;
